# TCL File Generated by Component Editor 12.0
# Sun Sep 30 14:58:53 CST 2012
# DO NOT MODIFY


# 
# Brush_motor_driver "Brush_motor_driver" v1.0
# Zhizhou Li 2012.09.30.14:58:53
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module Brush_motor_driver
# 
set_module_property NAME Brush_motor_driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "Zhizhou Li"
set_module_property DISPLAY_NAME Brush_motor_driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL brush_motor_driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file brush_motor_driver.v VERILOG PATH qsys_root/brush_motor_driver.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point MRST
# 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT
set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1


# 
# connection point MCLK
# 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0
set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressAlignment DYNAMIC
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock MCLK
set_interface_property ctrl associatedReset MRST
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl isMemoryDevice false
set_interface_property ctrl isNonVolatileStorage false
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl printableDevice false
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_address address Input 3
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1
add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_byteenable byteenable Input 4
add_interface_port ctrl avs_ctrl_readdata readdata Output 32


# 
# connection point motor_interface
# 
add_interface motor_interface conduit end
set_interface_property motor_interface associatedClock ""
set_interface_property motor_interface associatedReset ""
set_interface_property motor_interface ENABLED true

add_interface_port motor_interface HX export Output 1
add_interface_port motor_interface HY export Output 1

