# TCL File Generated by Component Editor 12.1sp1
# Sun Jun 23 18:34:59 CST 2013
# DO NOT MODIFY


# 
# qsys_device "qsys_device" v1.0
# Zhizhou Li 2013.06.23.18:34:59
# qsys device interface for outside qsys system
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module qsys_device
# 
set_module_property DESCRIPTION "qsys device interface for outside qsys system"
set_module_property NAME qsys_device
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "Zhizhou Li"
set_module_property DISPLAY_NAME qsys_device
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qsys_device
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file qsys_device.v VERILOG PATH qsys_root/qsys_device.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL qsys_device
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file qsys_device.v VERILOG PATH qsys_root/qsys_device.v


# 
# parameters
# 
add_parameter address_size INTEGER 8 ""
set_parameter_property address_size DEFAULT_VALUE 8
set_parameter_property address_size DISPLAY_NAME address_size
set_parameter_property address_size TYPE INTEGER
set_parameter_property address_size UNITS None
set_parameter_property address_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property address_size DESCRIPTION ""
set_parameter_property address_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point mrst
# 
add_interface mrst reset end
set_interface_property mrst associatedClock mclk
set_interface_property mrst synchronousEdges DEASSERT
set_interface_property mrst ENABLED true

add_interface_port mrst rsi_MRST_reset reset Input 1


# 
# connection point mclk
# 
add_interface mclk clock end
set_interface_property mclk clockRate 0
set_interface_property mclk ENABLED true

add_interface_port mclk csi_MCLK_clk clk Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock mclk
set_interface_property ctrl associatedReset mrst
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitStates 0
set_interface_property ctrl readWaitTime 0
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_address address Input address_size
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_gpio_byteenable byteenable Input 4
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point qsys_device
# 
add_interface qsys_device conduit end
set_interface_property qsys_device associatedClock mclk
set_interface_property qsys_device associatedReset mrst
set_interface_property qsys_device ENABLED true

add_interface_port qsys_device device_reset export Output 1
add_interface_port qsys_device device_clk export Output 1
add_interface_port qsys_device device_writedata export Output 8
add_interface_port qsys_device device_readdata export Input 8
add_interface_port qsys_device device_address export Output address_size
add_interface_port qsys_device device_read export Output 1
add_interface_port qsys_device device_write export Output 1
add_interface_port qsys_device device_waitrequest export Input 1

