# TCL File Generated by Component Editor 12.1sp1
# Sat Dec 14 18:32:17 PST 2013
# DO NOT MODIFY


# 
# SIO32 "SIO32" v1.0
# Zhizhou LI 2013.12.14.18:32:17
# serial IO extender
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module SIO32
# 
set_module_property DESCRIPTION "serial IO extender"
set_module_property NAME SIO32
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "Zhizhou LI"
set_module_property DISPLAY_NAME SIO32
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SIO32
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SIO32.v VERILOG PATH qsys_root/SIO32.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL SIO32
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SIO32.v VERILOG PATH qsys_root/SIO32.v


# 
# parameters
# 
add_parameter data_input STD_LOGIC_VECTOR 0
set_parameter_property data_input DEFAULT_VALUE 0
set_parameter_property data_input DISPLAY_NAME data_input
set_parameter_property data_input TYPE STD_LOGIC_VECTOR
set_parameter_property data_input UNITS None
set_parameter_property data_input ALLOWED_RANGES 0:3
set_parameter_property data_input HDL_PARAMETER true


# 
# display items
# 


# 
# connection point mrst
# 
add_interface mrst reset end
set_interface_property mrst associatedClock mclk
set_interface_property mrst synchronousEdges DEASSERT
set_interface_property mrst ENABLED true

add_interface_port mrst rsi_MRST_reset reset Input 1


# 
# connection point mclk
# 
add_interface mclk clock end
set_interface_property mclk clockRate 0
set_interface_property mclk ENABLED true

add_interface_port mclk csi_MCLK_clk clk Input 1


# 
# connection point gpio
# 
add_interface gpio avalon end
set_interface_property gpio addressUnits WORDS
set_interface_property gpio associatedClock mclk
set_interface_property gpio associatedReset mrst
set_interface_property gpio bitsPerSymbol 8
set_interface_property gpio burstOnBurstBoundariesOnly false
set_interface_property gpio burstcountUnits WORDS
set_interface_property gpio explicitAddressSpan 0
set_interface_property gpio holdTime 0
set_interface_property gpio linewrapBursts false
set_interface_property gpio maximumPendingReadTransactions 0
set_interface_property gpio readLatency 0
set_interface_property gpio readWaitTime 1
set_interface_property gpio setupTime 0
set_interface_property gpio timingUnits Cycles
set_interface_property gpio writeWaitTime 0
set_interface_property gpio ENABLED true

add_interface_port gpio avs_gpio_writedata writedata Input 32
add_interface_port gpio avs_gpio_readdata readdata Output 32
add_interface_port gpio avs_gpio_address address Input 3
add_interface_port gpio avs_gpio_byteenable byteenable Input 4
add_interface_port gpio avs_gpio_write write Input 1
add_interface_port gpio avs_gpio_read read Input 1
add_interface_port gpio avs_gpio_waitrequest waitrequest Output 1
set_interface_assignment gpio embeddedsw.configuration.isFlash 0
set_interface_assignment gpio embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment gpio embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment gpio embeddedsw.configuration.isPrintableDevice 0


# 
# connection point epl_bus
# 
add_interface epl_bus conduit end
set_interface_property epl_bus associatedClock mclk
set_interface_property epl_bus associatedReset mrst
set_interface_property epl_bus ENABLED true

add_interface_port epl_bus EPL_SCLK export Output 1
add_interface_port epl_bus EPL_SDI export Output 1
add_interface_port epl_bus EPL_SDO export Input 1
add_interface_port epl_bus EPL_SLE export Output 1
add_interface_port epl_bus EPL_INT export Input 1

