# TCL File Generated by Component Editor 12.0
# Sun Sep 30 23:44:44 CST 2012
# DO NOT MODIFY


# 
# Step_motor_driver "Step motor driver" v1.0
# Zhizhou Li 2012.09.30.23:44:44
# step motor driver
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module Step_motor_driver
# 
set_module_property DESCRIPTION "step motor driver"
set_module_property NAME Step_motor_driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "Zhizhou Li"
set_module_property DISPLAY_NAME "Step motor driver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL step_motor_driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file step_motor_driver.v VERILOG PATH qsys_root/step_motor_driver.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point MRST
# 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT
set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1


# 
# connection point MCLK
# 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0
set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressAlignment DYNAMIC
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock MCLK
set_interface_property ctrl associatedReset MRST
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl isMemoryDevice false
set_interface_property ctrl isNonVolatileStorage false
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl printableDevice false
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_byteenable byteenable Input 4
add_interface_port ctrl avs_ctrl_address address Input 3
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1


# 
# connection point PWMRST
# 
add_interface PWMRST reset end
set_interface_property PWMRST associatedClock MCLK
set_interface_property PWMRST synchronousEdges DEASSERT
set_interface_property PWMRST ENABLED true

add_interface_port PWMRST rsi_PWMRST_reset reset Input 1


# 
# connection point PWMCLK
# 
add_interface PWMCLK clock end
set_interface_property PWMCLK clockRate 0
set_interface_property PWMCLK ENABLED true

add_interface_port PWMCLK csi_PWMCLK_clk clk Input 1


# 
# connection point step_motor_interface
# 
add_interface step_motor_interface conduit end
set_interface_property step_motor_interface associatedClock MCLK
set_interface_property step_motor_interface associatedReset ""
set_interface_property step_motor_interface ENABLED true

add_interface_port step_motor_interface AX export Output 1
add_interface_port step_motor_interface AY export Output 1
add_interface_port step_motor_interface BX export Output 1
add_interface_port step_motor_interface BY export Output 1
add_interface_port step_motor_interface AE export Output 1
add_interface_port step_motor_interface BE export Output 1

